### ISSUE TITLE
How do you run the frontend ?

### ISSUE THREAD

**Issue by jektvik** [andissanayake/UnifiedApp#7]
The readme doesn't cover how to run the front-end and anything I try from package.json throws errors.

F.ex.
```
npm i

npm run dev
```

`Could not resolve "@ant-design/icons/es/icons/EyeOutlined"`

**Comment by andissanayake** [comment]
The steps you are following are correct. but we are not using Ant design icons for this project. You will able to fix this issue by installing `npm install @ant-design/icons --save`. But I hope this is due to an enhancement you are doing. Check Ant design icon [link ](https://ant.design/components/icon).  If I can be of any help, please do not hesitate to contact me.  Thanks.

**Comment by andissanayake** [comment]
Please check the last build [log](https://github.com/andissanayake/UnifiedApp/actions/runs/8394815647/job/22992752977), I have added web project build as well.
![image](https://github.com/andissanayake/UnifiedApp/assets/59598922/f01b48bb-90a5-4a70-a541-56868b4ef393)

**Comment by jektvik** [comment]
I'm unsure why this error triggered. Generally there's some kind of a dependency on ant-design in here:
https://github.com/search?q=repo%3Aandissanayake%2FUnifiedApp%20ant-design&type=code

but I've now moved on with the codebase quite a bit so unfortunatelly cannot reproduce anymore.

**Comment by andissanayake** [comment]
This issue is due to package-lock.json. I have removed that. Thank you @jektvik for bringing this to our attention.
